# fly.toml app configuration file generated for cl-usa-search on 2023-06-01T09:43:41-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app_name = "cl-usa-search"
app = "cl-usa-search"
primary_region = "lax"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
