
name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.1.24
      - run: flyctl deploy --remote-only
        env:
          app_name: cl-usa-search
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
